### ISSUE TITLE
error occur in log 

### ISSUE THREAD

**Issue by Wladislav** [jrbudda/Builder#10]
012-12-22 21:00:07 [INFO] WLAD_MC issued server command: /npc remove all
2012-12-22 21:00:21 [INFO] WLAD_MC issued server command: /npc create Builder --trait builder
2012-12-22 21:00:29 [INFO] WLAD_MC issued server command: /builder load house
2012-12-22 21:00:40 [INFO] WLAD_MC issued server command: /builder build
2012-12-22 21:00:40 [WARNING] [Builder] Task #12999 for Builder v0.6.5 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/Block
    at net.jrbudda.builder.Util.canStand(Util.java:332)
    at net.jrbudda.builder.BuilderTrait.findaspot(BuilderTrait.java:626)
    at net.jrbudda.builder.BuilderTrait.access$3(BuilderTrait.java:622)
    at net.jrbudda.builder.BuilderTrait$3.run(BuilderTrait.java:475)
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:530)
    at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
    at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
    at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
    at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)

**Comment by jrbudda** [comment]
Don't use a plugin for 1.4.5 on 1.4.6
