### ISSUE TITLE
Builder NPC just stands there but says building

### ISSUE THREAD

**Issue by Loki-Lokster** [jrbudda/Builder#13]
I dont know whats going on with it but when i select /builder load house then /builder build the NPC just stands there with a diamond pickaxe in its hand and when i type /builder info it says that its status is building yet i leave it for a while and still nothing? I have Citizens2.0.7 snapshot and the newest builder version and im running bukkit 1.4.7.

**Comment by jrbudda** [comment]
console errors?

**Comment by WoutDa** [comment]
I got this also.

Error message:

07:27:06 [INFO] kolewo issued server command: /builder build
07:27:06 [WARNING] [Builder] Task #234 for Builder v0.6.6 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_6/Block
    at net.jrbudda.builder.Util.canStand(Util.java:332)
    at net.jrbudda.builder.BuilderTrait.findaspot(BuilderTrait.java:630)
    at net.jrbudda.builder.BuilderTrait.access$3(BuilderTrait.java:626)
    at net.jrbudda.builder.BuilderTrait$3.run(BuilderTrait.java:479)
    at org.bukkit.craftbukkit.v1_5_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_5_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.v1_5_R1.MinecraftServer.r(MinecraftServer.java:512)
    at net.minecraft.server.v1_5_R1.DedicatedServer.r(DedicatedServer.java:225)
    at net.minecraft.server.v1_5_R1.MinecraftServer.q(MinecraftServer.java:476)
    at net.minecraft.server.v1_5_R1.MinecraftServer.run(MinecraftServer.java:409)
    at net.minecraft.server.v1_5_R1.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_6.Block
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more

**Comment by jrbudda** [comment]
Looks like youre running bulder for 1.4.7 on a newer version of craftbukkit
