### ISSUE TITLE
Unknown command

### ISSUE THREAD

**Issue by WoutDa** [jrbudda/Builder#19]
When typing "/trait builder" it says unknown command.

Sorry for bad English...

**Comment by jrbudda** [comment]
Do you have Citizens installed?

**Comment by WoutDa** [comment]
yes, Citizens works perfectly

Terminal:

Server Started at: 24/04/2013 17:35:36
229 recipes
27 achievements
17:35:36 [INFO] Starting minecraft server version 1.5
17:35:36 [INFO] Loading properties
17:35:36 [INFO] Default game type: SURVIVAL
17:35:36 [INFO] Generating keypair
17:35:36 [INFO] Starting Minecraft server on *:25565
17:35:37 [INFO] This server is running CraftBukkit version git-Bukkit-1.4.7-R1.0-45-g5c7d0bb-b2681jnks (MC: 1.5) (Implementing API version 1.5-R0.1-SNAPSHOT)
17:35:37 [SEVERE] Could not load 'plugins\PluginsBaker.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Vault
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.loadPlugins(CraftServer.java:239)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.<init(CraftServer.java:217)
    at net.minecraft.server.v1_5_R1.PlayerList.<init(PlayerList.java:56)
    at net.minecraft.server.v1_5_R1.DedicatedPlayerList.<init(SourceFile:11)
    at net.minecraft.server.v1_5_R1.DedicatedServer.init(DedicatedServer.java:105)
    at net.minecraft.server.v1_5_R1.MinecraftServer.run(MinecraftServer.java:381)
    at net.minecraft.server.v1_5_R1.ThreadServerApplication.run(SourceFile:573)
17:35:37 [SEVERE] Could not load 'plugins\Jailer.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/util/config/Configuration
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:182)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.loadPlugins(CraftServer.java:239)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.<init(CraftServer.java:217)
    at net.minecraft.server.v1_5_R1.PlayerList.<init(PlayerList.java:56)
    at net.minecraft.server.v1_5_R1.DedicatedPlayerList.<init(SourceFile:11)
    at net.minecraft.server.v1_5_R1.DedicatedServer.init(DedicatedServer.java:105)
    at net.minecraft.server.v1_5_R1.MinecraftServer.run(MinecraftServer.java:381)
    at net.minecraft.server.v1_5_R1.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NoClassDefFoundError: org/bukkit/util/config/Configuration
    at me.mahoutsukaii.plugins.jailer.Jailer.<init(Jailer.java:44)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:178)
    ... 9 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.util.config.Configuration
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 15 more
17:35:37 [SEVERE] Could not load 'plugins\iGates.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: PluginsBaker
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.loadPlugins(CraftServer.java:239)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.<init(CraftServer.java:217)
    at net.minecraft.server.v1_5_R1.PlayerList.<init(PlayerList.java:56)
    at net.minecraft.server.v1_5_R1.DedicatedPlayerList.<init(SourceFile:11)
    at net.minecraft.server.v1_5_R1.DedicatedServer.init(DedicatedServer.java:105)
    at net.minecraft.server.v1_5_R1.MinecraftServer.run(MinecraftServer.java:381)
    at net.minecraft.server.v1_5_R1.ThreadServerApplication.run(SourceFile:573)
17:35:37 [INFO] [MultiWorld] Loading MultiWorld v4.5.3
17:35:37 [INFO] [Citizens] Loading Citizens v1.2.4
17:35:37 [INFO] [bPermissions] Loading bPermissions v2.10.5
17:35:37 [INFO] [Hoams] Loading Hoams v1.0.1
17:35:37 [INFO] [BackToDeath] Loading BackToDeath v1.1
17:35:37 [INFO] [WorldEdit] Loading WorldEdit v5.5.5
17:35:37 [INFO] [Spawner] Loading Spawner v1.4
17:35:37 [INFO] [Slenderman] Loading Slenderman vB0.3.2_MC1.4.5_R0.2
17:35:37 [INFO] [CreativeGates] Loading CreativeGates v1.4
17:35:37 [INFO] [Waprs] Loading Waprs v1
17:35:37 [INFO] [MiningMachine] Loading MiningMachine v0.7.5
17:35:37 [INFO] [Builder] Loading Builder v0.6.6
17:35:37 [INFO] [MobArena] Loading MobArena v0.94.4.96
17:35:37 [INFO] [WorldGuard] Loading WorldGuard v5.7.3
17:35:37 [INFO] [MobileAdmin] Loading MobileAdmin v3.2.5
17:35:37 [INFO] [dynmap] Loading dynmap v1.6-646
17:35:37 [INFO] [MobRider] Loading MobRider v0.47.3-b3
17:35:37 [INFO] [Dynmap-WorldGuard] Loading Dynmap-WorldGuard v0.40
17:35:37 [INFO] [dynmap-mobs] Loading dynmap-mobs v0.50
17:35:37 [INFO] [CraftBook] Loading CraftBook v1873-bfe3918
17:35:37 [INFO] Preparing level "world"
17:35:37 [INFO] Preparing start region for level 0 (Seed: 6847595145147971611)
17:35:37 [INFO] ----- Bukkit Auto Updater -----
17:35:37 [INFO] It appears that you're running a Development Build, when you've specified in bukkit.yml that you prefer to run Recommended Builds.
17:35:37 [INFO] If you would like to be kept informed about new Development Build releases, it is recommended that you change 'preferred-channel' in your bukkit.yml to 'dev'.
17:35:37 [INFO] With that set, you will be told whenever a new version is available for download, so that you can always keep up to date and secure with the latest fixes.
17:35:37 [INFO] If you would like to disable this warning, simply set 'suggest-channels' to false in bukkit.yml.
17:35:37 [INFO] ----- ------------------- -----
17:35:38 [INFO] Preparing start region for level 1 (Seed: 6847595145147971611)
17:35:38 [INFO] Preparing spawn area: 91%
17:35:38 [INFO] Preparing start region for level 2 (Seed: 6847595145147971611)
17:35:38 [INFO] [MultiWorld] Enabling MultiWorld v4.5.3
17:35:38 [INFO] Preparing start region for level 3 (Seed: 7464778026040624732)
17:35:38 [INFO] Preparing start region for level 4 (Seed: -1568860533487830018)
17:35:39 [INFO] [MultiWorld] v4.5.3 enabled.
17:35:39 [INFO] [Citizens] Enabling Citizens v1.2.4
17:35:39 [INFO] [Citizens] NPC types loaded: blacksmith, guard, healer, quester, trader, wizard
17:35:40 [INFO] [Citizens] Vault is required for economy but wasn't found. Server economy is unavailable.
17:35:40 [INFO] [Citizens] version [1.2.4] loaded.
17:35:40 [INFO] [bPermissions] Enabling bPermissions v2.10.5
17:35:40 [INFO] [Hoams] Enabling Hoams v1.0.1
17:35:40 [INFO] [BackToDeath] Enabling BackToDeath v1.1
17:35:40 [INFO] [BackToDeath] BackToDeath has been enabled!
17:35:40 [INFO] [WorldEdit] Enabling WorldEdit v5.5.5
17:35:40 [INFO] WEPIF: bPermissions detected! Using bPermissions for permissions
17:35:40 [INFO] [Spawner] Enabling Spawner v1.4
17:35:40 [INFO] [Slenderman] Enabling Slenderman vB0.3.2_MC1.4.5_R0.2
17:35:40 [INFO] [CreativeGates] Enabling CreativeGates v1.4
17:35:40 [INFO] [CreativeGates v1.4] === ENABLE START ===
17:35:40 [INFO] [CreativeGates v1.4] === ENABLE DONE (Took 50ms) ===
17:35:40 [INFO] [Waprs] Enabling Waprs v1
17:35:40 [INFO] [Warps] Enabled
17:35:40 [INFO] [MiningMachine] Enabling MiningMachine v0.7.5
17:35:40 [INFO] [Builder] Enabling Builder v0.6.6
17:35:40 [INFO] [Builder] Builder could not register with Denizen
17:35:40 [SEVERE] Error occurred while enabling Builder v0.6.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
    at net.jrbudda.builder.Builder.onEnable(Builder.java:64)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.loadPlugin(CraftServer.java:282)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.enablePlugins(CraftServer.java:264)
    at net.minecraft.server.v1_5_R1.MinecraftServer.j(MinecraftServer.java:303)
    at net.minecraft.server.v1_5_R1.MinecraftServer.e(MinecraftServer.java:282)
    at net.minecraft.server.v1_5_R1.MinecraftServer.a(MinecraftServer.java:242)
    at net.minecraft.server.v1_5_R1.DedicatedServer.init(DedicatedServer.java:150)
    at net.minecraft.server.v1_5_R1.MinecraftServer.run(MinecraftServer.java:381)
    at net.minecraft.server.v1_5_R1.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensAPI
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 12 more
17:35:40 [INFO] [MobArena] Enabling MobArena v0.94.4.96
17:35:40 [WARNING] [MobArena] Vault was not found. Economy rewards will not work!
17:35:40 [WARNING] [MobArena] Recurrent wave 'new_wave' in arena 'default' is missing either the 'frequency' or the 'priority' node. Skipping...
17:35:40 [INFO] [MobArena] Loaded arena 'default'.
17:35:40 [INFO] [MobArena] v0.94.4.96 enabled.
17:35:40 [INFO] [WorldGuard] Enabling WorldGuard v5.7.3
17:35:40 [INFO] [WorldGuard](world) TNT ignition is PERMITTED.
17:35:40 [INFO] [WorldGuard](world) Lighters are PERMITTED.
17:35:40 [INFO] [WorldGuard](world) Lava fire is blocked.
17:35:40 [INFO] [WorldGuard](world) Fire spread is UNRESTRICTED.
17:35:40 [INFO] [WorldGuard] Loaded configuration for world 'world'
17:35:40 [INFO] [WorldGuard](world_nether) TNT ignition is PERMITTED.
17:35:40 [INFO] [WorldGuard](world_nether) Lighters are PERMITTED.
17:35:40 [INFO] [WorldGuard](world_nether) Lava fire is blocked.
17:35:40 [INFO] [WorldGuard](world_nether) Fire spread is UNRESTRICTED.
17:35:40 [INFO] [WorldGuard] Loaded configuration for world 'world_nether'
17:35:40 [INFO] [WorldGuard](world_the_end) TNT ignition is PERMITTED.
17:35:40 [INFO] [WorldGuard](world_the_end) Lighters are PERMITTED.
17:35:40 [INFO] [WorldGuard](world_the_end) Lava fire is blocked.
17:35:40 [INFO] [WorldGuard](world_the_end) Fire spread is UNRESTRICTED.
17:35:40 [INFO] [WorldGuard] Loaded configuration for world 'world_the_end'
17:35:40 [INFO] [WorldGuard](poep) TNT ignition is PERMITTED.
17:35:40 [INFO] [WorldGuard](poep) Lighters are PERMITTED.
17:35:40 [INFO] [WorldGuard](poep) Lava fire is blocked.
17:35:40 [INFO] [WorldGuard](poep) Fire spread is UNRESTRICTED.
17:35:40 [INFO] [WorldGuard] Loaded configuration for world 'poep'
17:35:40 [INFO] [WorldGuard](kingdom) TNT ignition is PERMITTED.
17:35:40 [INFO] [WorldGuard](kingdom) Lighters are PERMITTED.
17:35:40 [INFO] [WorldGuard](kingdom) Lava fire is blocked.
17:35:40 [INFO] [WorldGuard](kingdom) Fire spread is UNRESTRICTED.
17:35:40 [INFO] [WorldGuard] Loaded configuration for world 'kingdom'
17:35:40 [INFO] [WorldGuard] 1 regions loaded for 'world'
17:35:40 [INFO] [WorldGuard] 0 regions loaded for 'world_nether'
17:35:40 [INFO] [WorldGuard] 0 regions loaded for 'world_the_end'
17:35:40 [INFO] [WorldGuard] 0 regions loaded for 'poep'
17:35:40 [INFO] [WorldGuard] 0 regions loaded for 'kingdom'
17:35:40 [INFO] [MobileAdmin] Enabling MobileAdmin v3.2.5
17:35:40 [INFO] [MobileAdmin] Loading server stats.
17:35:40 [INFO] [MobileAdmin] Loading chat log.
17:35:40 [INFO] [MobileAdmin] Loading users.
17:35:40 [INFO] [MobileAdmin] Starting server...
17:35:40 [INFO] [MobileAdmin] Version 3.2.5 is enabled!
17:35:40 [INFO] [dynmap] Enabling dynmap v1.6-646
17:35:40 [INFO] [MobileAdmin] Server listening on *:5839
17:35:40 [INFO] [dynmap] Using bPermissions 2.10.5 for access control
17:35:41 [INFO] [dynmap] Loaded 21 shaders.
17:35:41 [INFO] [dynmap] Loaded 82 perspectives.
17:35:41 [INFO] [dynmap] Loaded 12 lightings.
17:35:41 [INFO] [dynmap] Web server started on address 0.0.0.0:8123
17:35:41 [INFO] [dynmap] version 1.6-646 is enabled - core version 1.6-1624
17:35:41 [INFO] [dynmap] Loaded 3 maps of world 'world'.
17:35:41 [INFO] [dynmap] Loaded 6 pending tile renders for world 'world
17:35:41 [INFO] [dynmap] Loaded 2 maps of world 'world_nether'.
17:35:41 [INFO] [dynmap] Loaded 2 maps of world 'world_the_end'.
17:35:41 [INFO] [dynmap] Loaded 3 maps of world 'poep'.
17:35:41 [INFO] [dynmap] Loaded 3 maps of world 'kingdom'.
17:35:41 [INFO] [dynmap] Enabled
17:35:41 [INFO] [MobRider] Enabling MobRider v0.47.3-b3
17:35:41 [WARNING] [MobRider] Did not find plugin Vault
17:35:41 [INFO] [MobRider] Found plugin WorldGuard
17:35:41 [WARNING] [MobRider] Did not find plugin Residence
17:35:41 [INFO] [MobRider] Found plugin Citizens
17:35:41 [WARNING] [MobRider] Did not find plugin Towny
17:35:41 [WARNING] [MobRider] Did not find plugin Factions
17:35:41 [WARNING] [MobRider] Did not find plugin Spout
17:35:41 [WARNING] [MobRider] Did not find plugin Regios
17:35:41 [WARNING] [MobRider] Did not find plugin Multiverse-Core
17:35:41 [WARNING] [MobRider] Did not find permission provider
17:35:41 [WARNING] [MobRider] Did not find economy provider
17:35:41 [INFO] [MobRider] 0.47.3-b3 enabled.
17:35:41 [INFO] [Dynmap-WorldGuard] Enabling Dynmap-WorldGuard v0.40
17:35:41 [INFO] [Dynmap-WorldGuard] initializing
17:35:41 [INFO] [Dynmap-WorldGuard] version 0.40 is activated
17:35:41 [INFO] [dynmap-mobs] Enabling dynmap-mobs v0.50
17:35:41 [INFO] [dynmap-mobs] initializing
17:35:41 [INFO] [dynmap-mobs] Enable layer for mobs
17:35:41 [INFO] [dynmap-mobs] Enable layer for vehicles
17:35:41 [INFO] [dynmap-mobs] version 0.50 is activated
17:35:41 [INFO] [CraftBook] Enabling CraftBook v1873-bfe3918
17:35:41 [INFO] 1 cauldron recipe(s) loaded
17:35:41 [INFO] [CraftBook] Registered a new shapeless recipe!
17:35:41 [INFO] [CraftBook] Registered a new shaped recipe!
17:35:41 [INFO] [CraftBook] Registered a new furnace recipe!
17:35:41 [INFO] [CraftBook] Registered 3 custom recipes!
17:35:41 [WARNING] [CraftBook] Chairs require ProtocolLib! They will not function without it!
17:35:41 [INFO] [CraftBook] Enumerating chunks for self-triggered components...
17:35:41 [INFO] [WorldEdit] Using external NmsBlock for this version: CBXNmsBlock_15
17:35:41 [INFO] [CraftBook] 3125 chunk(s) for 5 world(s) processed (49ms elapsed)
17:35:41 [WARNING] Server permissions file permissions.yml is not valid YAML.
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.loadCustomPermissions(CraftServer.java:626)
    at org.bukkit.craftbukkit.v1_5_R1.CraftServer.enablePlugins(CraftServer.java:270)
    at net.minecraft.server.v1_5_R1.MinecraftServer.j(MinecraftServer.java:303)
    at net.minecraft.server.v1_5_R1.MinecraftServer.e(MinecraftServer.java:282)
    at net.minecraft.server.v1_5_R1.MinecraftServer.a(MinecraftServer.java:242)
    at net.minecraft.server.v1_5_R1.DedicatedServer.init(DedicatedServer.java:150)
    at net.minecraft.server.v1_5_R1.MinecraftServer.run(MinecraftServer.java:381)
    at net.minecraft.server.v1_5_R1.ThreadServerApplication.run(SourceFile:573)
17:35:41 [INFO] Done (4.498s)! For help, type "help" or "?"
17:35:42 [INFO] [Citizens] Loaded 1 NPCs.
17:35:42 [INFO] [Citizens] Loaded 0 quests.
17:35:43 [INFO] CraftBook v3.6.1

**Comment by WoutDa** [comment]
when "/builder load {shematic_name}" it says internal error

**Comment by jrbudda** [comment]
you're using citizens 1.

**Comment by WoutDa** [comment]
citizens 2 dont work

**Comment by jrbudda** [comment]
Builder is a character for Citizens2 and does not work with Citizens 1.

**Comment by WoutDa** [comment]
when i install citizens 2 and type a command, nothing happens, just blankness

**Comment by jrbudda** [comment]
Check your startup for errors, otherwise I dunno you'll have to ask Citizens support.

**Comment by WoutDa** [comment]
it says citizens is not compatible with minecraft 1.5.
And the webpage for citizens supports give's an error 404
