### ISSUE TITLE
/builder build not working

### ISSUE THREAD

**Issue by wickeddude1** [jrbudda/Builder#40]
[23:22:24] [Server thread/INFO]: DandelionDonkey issued server command: /builder build
[23:22:24] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'builder' in plugin Builder v0.9.1
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Bukkit-6e0120a]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[minecraft_server.jar:git-Bukkit-6e0120a]
    at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:625) ~[minecraft_server.jar:git-Bukkit-6e0120a]
    at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1077) [minecraft_server.jar:git-Bukkit-6e0120a]
    at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:937) [minecraft_server.jar:git-Bukkit-6e0120a]
    at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(SourceFile:37) [minecraft_server.jar:git-Bukkit-6e0120a]
    at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(SourceFile:9) [minecraft_server.jar:git-Bukkit-6e0120a]
    at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Bukkit-6e0120a]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
    at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [minecraft_server.jar:git-Bukkit-6e0120a]
    at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:670) [minecraft_server.jar:git-Bukkit-6e0120a]
    at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336) [minecraft_server.jar:git-Bukkit-6e0120a]
    at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626) [minecraft_server.jar:git-Bukkit-6e0120a]
    at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534) [minecraft_server.jar:git-Bukkit-6e0120a]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/NBTBase
    at net.jrbudda.builder.BuilderSchematic.BuildQueue(BuilderSchematic.java:95) ~[?:?]
    at net.jrbudda.builder.BuilderTrait.StartBuild(BuilderTrait.java:346) ~[?:?]
    at net.jrbudda.builder.BuilderTrait.TryBuild(BuilderTrait.java:288) ~[?:?]
    at net.jrbudda.builder.Builder.onCommand(Builder.java:468) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Bukkit-6e0120a]
    ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R4.NBTBase
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[minecraft_server.jar:git-Bukkit-6e0120a]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[minecraft_server.jar:git-Bukkit-6e0120a]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
    at net.jrbudda.builder.BuilderSchematic.BuildQueue(BuilderSchematic.java:95) ~[?:?]
    at net.jrbudda.builder.BuilderTrait.StartBuild(BuilderTrait.java:346) ~[?:?]
    at net.jrbudda.builder.BuilderTrait.TryBuild(BuilderTrait.java:288) ~[?:?]
    at net.jrbudda.builder.Builder.onCommand(Builder.java:468) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Bukkit-6e0120a]
    ... 15 more
citizens version 1.0.15
builder latest 1.7.10 version
bukkit 1.8.3
any ideas?

**Comment by noorkoteb** [comment]
i got this too

using citizens latest build for 1.8.6 and latest build for builders for 1.7.9

**Comment by Talamar1** [comment]
Try this build:
http://ci.citizensnpcs.co/job/Builder/lastSuccessfulBuild/artifact/target/Builder.jar

**Comment by adamwbb** [comment]
the new build is not working. it isn't even detected by the server
