### ISSUE TITLE
An internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by Thefirebeast** [jrbudda/Builder#48]
[Error.txt](https://github.com/jrbudda/Builder/files/1500847/Error.txt)
12:41:10 AM [INFO] thefirebeast99 issued server command: /builder build
12:41:10 AM [ERROR] null
12:41:10 AM org.bukkit.command.CommandException: Unhandled exception executing command 'builder' in plugin Builder v0.9.1
12:41:10 AM at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:10 AM at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
12:41:11 AM at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
12:41:11 AM at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
12:41:11 AM Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/NBTBase
12:41:11 AM at net.jrbudda.builder.EmptyBuildBlock.getMat(EmptyBuildBlock.java:19) ~[?:?]
12:41:11 AM at net.jrbudda.builder.BuilderSchematic.BuildQueue(BuilderSchematic.java:61) ~[?:?]
12:41:11 AM at net.jrbudda.builder.BuilderTrait.StartBuild(BuilderTrait.java:346) ~[?:?]
12:41:11 AM at net.jrbudda.builder.BuilderTrait.TryBuild(BuilderTrait.java:288) ~[?:?]
12:41:11 AM at net.jrbudda.builder.Builder.onCommand(Builder.java:467) ~[?:?]
12:41:11 AM at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM ... 15 more
12:41:11 AM Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.NBTBase
12:41:11 AM at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:11 AM at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:12 AM at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
12:41:12 AM at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
12:41:12 AM at net.jrbudda.builder.EmptyBuildBlock.getMat(EmptyBuildBlock.java:19) ~[?:?]
12:41:12 AM at net.jrbudda.builder.BuilderSchematic.BuildQueue(BuilderSchematic.java:61) ~[?:?]
12:41:12 AM at net.jrbudda.builder.BuilderTrait.StartBuild(BuilderTrait.java:346) ~[?:?]
12:41:12 AM at net.jrbudda.builder.BuilderTrait.TryBuild(BuilderTrait.java:288) ~[?:?]
12:41:12 AM at net.jrbudda.builder.Builder.onCommand(Builder.java:467) ~[?:?]
12:41:12 AM at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-19ed80c]
12:41:12 AM ... 15 more

**Comment by Zeuscp1** [comment]
same here!

**Comment by masonbesmer** [comment]
i third this

`[20:57:05] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'builder' in plugin Builder v0.9.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Bukkit-d0a3620]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[minecraft_server.jar:git-Bukkit-d0a3620]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:628) ~[minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1338) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1198) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Bukkit-d0a3620]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [minecraft_server.jar:git-Bukkit-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [minecraft_server.jar:git-Bukkit-d0a3620]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_10_R1/Block
at net.jrbudda.builder.EmptyBuildBlock.getMat(EmptyBuildBlock.java:19) ~[?:?]
at net.jrbudda.builder.BuilderSchematic.BuildQueue(BuilderSchematic.java:61) ~[?:?]
at net.jrbudda.builder.BuilderTrait.StartBuild(BuilderTrait.java:347) ~[?:?]
at net.jrbudda.builder.BuilderTrait.TryBuild(BuilderTrait.java:289) ~[?:?]
at net.jrbudda.builder.Builder.onCommand(Builder.java:458) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Bukkit-d0a3620]
... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.Block
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[minecraft_server.jar:git-Bukkit-d0a3620]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76) ~[minecraft_server.jar:git-Bukkit-d0a3620]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
at net.jrbudda.builder.EmptyBuildBlock.getMat(EmptyBuildBlock.java:19) ~[?:?]
at net.jrbudda.builder.BuilderSchematic.BuildQueue(BuilderSchematic.java:61) ~[?:?]
at net.jrbudda.builder.BuilderTrait.StartBuild(BuilderTrait.java:347) ~[?:?]
at net.jrbudda.builder.BuilderTrait.TryBuild(BuilderTrait.java:289) ~[?:?]
at net.jrbudda.builder.Builder.onCommand(Builder.java:458) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Bukkit-d0a3620]
... 15 more`
