### ISSUE TITLE
Builder's loading large schematics

### ISSUE THREAD

**Issue by Ruberb** [jrbudda/Builder#9]
Hi there, I recently tried using larger than normal schematics and i want an NPC to build them as pasting them crashes the server, though the NPC wont load it and it says there is an internal error.

How can I fix it?
Is it a matter of needing more RAM?

**Comment by jrbudda** [comment]
An internal error on /builder load should have some kind of error shown in the console. You'll need to find that error and paste it here or use pastebin.com. I don't know what the problem could be otherwise.

**Comment by Ruberb** [comment]
dleCommand(NetServerHandler.java:880)
at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:826)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:808)
at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
at net.minecraft.server.ServerConnection.b(SourceFile:35)
at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.OutOfMemoryError: Java heap space
at net.jrbudda.builder.MCEditSchematicFormat.load(MCEditSchematicFormat.java:151)
at net.jrbudda.builder.Builder.onCommand(Builder.java:560)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)

Thats all I got

**Comment by jrbudda** [comment]
Ah.. out of memory error, that would do it... just how big IS that schematic?

**Comment by Ruberb** [comment]
Its 33kb, which is worrying considering i want to do schematics that are 300+kb.

So what can I do to fix it? just Upgrade RAM?

**Comment by jrbudda** [comment]
I meant dimension-wise, the size of the file is not necessarily the same as how big it is in-game. And yes more ram would fix it, keeping in mind that you have to explicitly tell java how much RAM to allocate to minecraft server

**Comment by mrdragalion** [comment]
The best thing here would be to ask how much RAM your MC server is using.

I was able to import and build schem's that we're 200x200 big with 2GB permitted. And even then it never went past 1GB. try -Xincgc instead of -Xms###M (### being the number) this is the java command that set's the mimimum memory, -Xincgc allows Java to use as little memory as it needs to. I've seen some issue's where it's being forced to use a set memory and plugins do not like that)

**Comment by Ruberb** [comment]
I host my server on Ausfrag, and SInce its only me and about 4 other people we only have 256mb RAM. So I am guessing when youre talking about your server having 2gb it was localhost?

**Comment by jrbudda** [comment]
ooh, wow 256 is very, very very small for a minecraft server, its a memory hog as-is before trying to load a couple million blocks from a schematic.

**Comment by Ruberb** [comment]
its only for building and we dont have any problems with lag only big Worldedit things crash it. Ill look into upgrading and report back
